name: Selenium Automation Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest selenium webdriver-manager

      # 4️⃣ Run Selenium tests
      - name: Run Selenium tests
        run: |
          # Set CI environment variable for headless
          export CI=true
          pytest -v --disable-warnings --maxfail=1 --alluredir=reports
