name: Selenium Automation Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest selenium webdriver-manager

      # 4️⃣ Set up Chrome and ChromeDriver
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # 5️⃣ Run pytest in headless mode
      - name: Run Selenium tests
        run: |
          pytest -v --headless --disable-warnings --maxfail=1
